---
title: "Simulate Demographic stochasticity"
author: Michelle DePrenger-Levin
---


```{r, eval = FALSE}
detectCores() 
registerDoParallel(10) 

StPopSz <- c(50,100,500)
sig2d <- seq(0.001, 1e-5, length.out = 3)
sampsz <- 999
Y <- 100

PopDyn.lh.sig.popsz <- 
  foreach(SPS = StPopSz, .packages = c("popbio","foreach"), .combine = c, 
          .multicombine = TRUE) %dopar% {
    foreach(s2s = sig2d) %dopar% {   
      foreach(rowN = 1:nrow(lh)) %do% {      
        
        MPMs1 <- MPM_stoch(sampsz = sampsz, age1 = lh$age[rowN],
                           p_a = lh$P_a[rowN], p_j = lh$P_j[rowN],
                           m1 = lh$m[rowN], sig2D = s2s)
        
        lmbds <- data.frame(age = lh$age[rowN],
                            p_j = lh$P_j[rowN],
                            p_a = lh$P_a[rowN],
                            m = lh$m[rowN],
                            sig2D = s2s,
                            Lambda = unlist(lapply(MPMs1, function(x) lambda(x))),
                            TraitSpsig2D = unlist(lapply(MPMs1, function(x) sig2Dts.A(x))))
        
        PopDyn <- ER(MPMs = MPMs1, Y = Y, StPopSz = SPS, sig2D = s2s,
                     age1 = lh$age[rowN],
                     p_a = lh$P_a[rowN],
                     p_j = lh$P_j[rowN],
                     m1 = lh$m[rowN])
        
        Time2Ext <- data.frame(A_LH = rowN, do.call(rbind, lapply(PopDyn, function(er){
          er[nrow(er),]
          })))
    list(lmbds, Time2Ext)
      }
    }
  }

lmbds.demo <- do.call(rbind,lapply(PopDyn.lh.sig.popsz, function(i1){
  i1out <- do.call(rbind, lapply(i1, function(i2){
    i2[[1]]
  }))
  i1out
}))

PopDyn.demo <- do.call(rbind,lapply(PopDyn.lh.sig.popsz, function(i1){
  i1out <- do.call(rbind, lapply(i1, function(i2){
    i2[[2]]
  }))
  i1out
}))

rm(PopDyn.lh.sig.popsz)
gc()
```


```{r}
# Bins and categories
lmbds.demo$parity <- ifelse(lmbds.demo$p_a == 0, "semel", "itero")
lmbds.demo$agebin <- cut_number(lmbds.demo$age, 3)

lmbds.demo$mbin <- ifelse(lmbds.demo$m < 16, 
                          as.character(cut_number(lmbds.demo$m[lmbds.demo$m < 16], 3)), 
                            as.character(cut_number(lmbds.demo$m[lmbds.demo$m > 15], 3)))
lmbds.demo$mbin <- factor(lmbds.demo$mbin, 
                          levels = levels(as.factor(lmbds.demo$mbin))[c(5,1,4,6,3,2)])
lmbds.demo$pjbin <- cut_number(lmbds.demo$p_j, 3) # groups with ca == # obs
lmbds.demo$pabin <- ifelse(lmbds.demo$p_a == 0, "[0,0]", "(0,0.95]")# cut_number(lmbds.demo$p_a, 2)
lmbds.demo$pabin <- as.character(lmbds.demo$pabin)
lmbds.demo$pabin[lmbds.demo$parity == "itero"] <- 
  as.character(cut_number(lmbds.demo$p_a[lmbds.demo$parity == "itero"], 3))
lmbds.demo$pabin <- factor(lmbds.demo$pabin, 
                            levels = levels(as.factor(lmbds.demo$pabin))[c(3,4,1,2)])


colfunc<-colorRampPalette(c("red","yellow","springgreen","royalblue"))

## difference from 1 in lambda by life history
demoPla <- ggplot(lmbds.demo, aes(y = (Lambda-1), x= as.factor(sig2D), colour = as.factor(agebin)))+
  geom_boxplot()+
  theme_bw()+
  facet_grid(~parity)+
  ylab(expression(Delta~lambda))+
  scale_color_manual(expression(alpha), values = colfunc(3))+ # guide = "none")+ #
  # xlab(expression(sigma[D]^2))+
  xlab("")+
  ggtitle("a)")
  
demoPlb <- ggplot(lmbds.demo, aes(y= (Lambda-1), x= as.factor(sig2D), colour = pjbin))+
  geom_boxplot()+
  theme_bw()+
  facet_grid(~parity)+
  ylab(expression(Delta~lambda))+
  scale_color_manual(expression(P[j]),
                     values = colfunc(3))+
  xlab("")+
  ggtitle("b)")

demoPlc <- ggplot(lmbds.demo, aes(y=(Lambda-1), x= as.factor(sig2D), colour = mbin))+
  geom_boxplot()+
  theme_bw()+
  facet_grid(~parity)+
  ylab(expression(Delta~lambda))+
  scale_color_manual(expression(m), values = colfunc(6))+
  xlab(expression(sigma[D]^2))+
  ggtitle("c)")

demoPld <- ggplot(lmbds.demo, aes(y=(Lambda-1), x= as.factor(sig2D), colour = pabin))+
  geom_boxplot()+
  theme_bw()+
  facet_grid(~parity)+
  ylab(expression(Delta~lambda))+
  scale_color_manual(expression(P[a]), values = colfunc(4))+
  xlab(expression(sigma[D]^2))+
  ggtitle("d)")


 (demoPla + demoPlb)/(demoPlc + demoPld)

rm(lmbds.demo)
gc()

```


#################### 2022-03-01 #################### 

```{r}
# Bins and categories
PopDyn.demo$parity <- "itero"
PopDyn.demo$parity[PopDyn.demo$p_a == 0] <- "semel"
PopDyn.demo$pjbin <- cut_number(PopDyn.demo$p_j, 3) # groups with ca == # obs
PopDyn.demo$pabin <- ifelse(PopDyn.demo$p_a == 0, "[0,0]", 
                            as.character(cut_number(PopDyn.demo$p_a[PopDyn.demo$p_a > 0], 3)))
PopDyn.demo$pabin <- factor(PopDyn.demo$pabin, 
                            levels = levels(as.factor(PopDyn.demo$pabin))[c(3,4,1,2)])

PopDyn.demo$agebin <-  cut_number(PopDyn.demo$age, 3)

PopDyn.demo$mbin <- ifelse(PopDyn.demo$m < 16, 
                           as.character(cut(PopDyn.demo$m[PopDyn.demo$m < 16], 
                                            breaks = c(0,2,5,15))), 
                            as.character(cut_number(PopDyn.demo$m[PopDyn.demo$m > 15], 3)))
PopDyn.demo$mbin <- factor(PopDyn.demo$mbin, 
                             levels = levels(as.factor(PopDyn.demo$mbin))[c(1,2,5,6,4,3)],
                           labels = c("[1,2]",levels(as.factor(PopDyn.demo$mbin))[c(2,5,6,4,3)]))


colfunc<-colorRampPalette(c("red","gold","springgreen","royalblue"))
```

```{r}
Time2Extc <- ggplot(PopDyn.demo, aes(Year, colour = mbin, group = as.factor(mbin)))+
  stat_ecdf(size = 1)+
  theme_bw()+
  facet_grid(sig2D ~ parity + StPopSz)+
  scale_colour_manual(expression(m),
                      values = colfunc(6))+
  coord_cartesian(xlim = c(0,93), ylim = c(0,0.35))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  xlab("Year")+
  ggtitle("c)")+
  ylab("Extinction Risk")


Time2Exta <- ggplot(PopDyn.demo, aes(Year, colour = agebin, group = as.factor(agebin)))+
  stat_ecdf(size = 1)+
  theme_bw()+
  facet_grid(sig2D ~ parity + StPopSz, scales = "free")+ # p_j = row, p_a = col
  # scale_colour_discrete(expression(m[fecundity]))+
  scale_colour_manual(expression(alpha),values = colfunc(3))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_cartesian(xlim = c(0,93), ylim = c(0,0.4))+
  # xlab("Year")+
  xlab("")+
  ggtitle("a)")+
  ylab("Extinction Risk")
  

Time2Extb <- ggplot(PopDyn.demo, aes(Year, colour = pjbin))+
  stat_ecdf(size=1)+
  theme_bw()+
  facet_grid(sig2D ~ parity + StPopSz)+
  scale_color_manual(expression(P[j]),values=colfunc(3))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_cartesian(xlim = c(0,93), ylim = c(0,0.4))+
  xlab("")+
  ggtitle("b)")+
  ylab("")

Time2Extd <- ggplot(PopDyn.demo, aes(Year, colour = pabin))+
  stat_ecdf(size = 1)+
  theme_bw()+
  facet_grid(sig2D ~ parity + StPopSz)+
  scale_color_manual(expression(P[a]),values=colfunc(4))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  coord_cartesian(xlim = c(0,93), ylim = c(0,0.3))+
  xlab("Year")+
  ggtitle("d)")+
  ylab("")

  (Time2Exta + Time2Extb)/(Time2Extc + Time2Extd)

```


```{r}
ProbExt.demo <- do.call(rbind,lapply(split(PopDyn.demo, list(PopDyn.demo$A_LH,
                                                             PopDyn.demo$StPopSz,
                                                             PopDyn.demo$sig2D)), 
                     function(x){
                     data.frame(A_LH = x$A_LH[1], StPopSz = x$StPopSz[1], sig2d = x$sig2D[1],
                                age = x$age[1], m = x$m[1], p_a = x$p_a[1], p_j = x$p_j[1],
                                mbin = x$mbin[1], parity = x$parity[1], pjbin = x$pjbin[1],
                                pabin = x$pabin[1], agebin = x$agebin[1],
                                ProbExt100yrs = sum(x$Ext)/nrow(x),
                                ProbExt30yrs = sum(x$Ext[x$Year < 31])/nrow(x),
                                ProbExt10yrs = sum(x$Ext[x$Year < 11])/nrow(x)) 
                       }))

```

```{r}
EPa <- ggplot(ProbExt.demo, aes(x = as.factor(sig2d), ProbExt10yrs, color = as.factor(agebin)))+
  geom_boxplot()+
  theme_bw()+
  scale_color_manual(expression(alpha), values = colfunc(3))+
  facet_grid(parity ~  StPopSz)+
  xlab(expression(sigma[D]^2))+
  ylab("EP (10 years)")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ggtitle("a)")

EPb <- ggplot(ProbExt.demo, aes(x = as.factor(sig2d),
                                   ProbExt10yrs, colour = as.factor(pjbin)))+
  geom_boxplot()+
  theme_bw()+
  scale_color_manual(expression(P[j]), values = colfunc(4))+
  facet_grid(parity ~  StPopSz)+
  xlab(expression(sigma[D]^2))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("EP (10 years)")+
  ggtitle("b)")
EPc <- ggplot(ProbExt.demo, aes(x = as.factor(sig2d),
                                   ProbExt10yrs, colour = as.factor(mbin)))+
  geom_boxplot()+
  theme_bw()+
  scale_color_manual(expression(m), values = colfunc(6))+
  facet_grid(parity ~  StPopSz)+
  xlab(expression(sigma[D]^2))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("EP (10 years)")+
  ggtitle("c)")
EPd <- ggplot(ProbExt.demo, aes(x = as.factor(sig2d),
                                   ProbExt10yrs, colour = as.factor(pabin)))+
  geom_boxplot()+
  scale_color_manual(expression(P[a]), values = colfunc(4))+
  theme_bw()+
  facet_grid(parity ~  StPopSz)+
  xlab(expression(sigma[D]^2))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("EP (10 years)")+
  ggtitle("c)")

  (EPa + EPb)/(EPc + EPd)+
  plot_annotation(title = "Demographic Stochasticity",
                  caption = expression("m: fecudnity;"~alpha*": age of reproductive maturity;"~P[j]*": juvenile survival;"~P[a]~": adult survival"))

```

```{r}
gc()

lmbds.demo$mbin <- cut_interval(lmbds.demo$m, length = 100)
lmbds.demo$parity <- "itero"
lmbds.demo$parity[lmbds.demo$p_a == 0] <- "semel"
lmbds.demo$pjbin <- cut_number(lmbds.demo$p_j, 3)
lmbds.demo$pabin <- cut_number(lmbds.demo$p_a, 2)
 
ggplot(lmbds.demo, aes(Lambda, fill = mbin, group = mbin), alpha = 0.5)+
  geom_histogram(binwidth = 0.05)+
  theme_bw()+
  facet_grid(pjbin + sig2D ~ pabin + parity, scales = "free")+ # p_j = row, p_a = col
  scale_fill_discrete(expression(m[fecundity]))

```

